### ISSUE TITLE
GitHub Actions: combine build and lint steps

### ISSUE THREAD

**Issue by warriordog** [warriordog/mooltipage#56]
These were originally separated when the lint-full profile still existed, because lint-full took several minutes. But now a lint only takes a few seconds, so the steps can be combined.

**Comment by Vhndaree** [comment]
@warriordog, Can you explain more, I think current gh actions build, run tests and lint the code. I am not clear about combining lint and build.

**Comment by warriordog** [comment]
@Vhndaree Oh this was already done at some point, sorry. At one point the "build-all" job (I also used the wrong terminology here) was actually two jobs - "build-test" and "lint". This issue is unneeded.
