### ISSUE TITLE
Implement pre-commit hook. Either precommit or husky.

### ISSUE THREAD

**Issue by Vhndaree** [warriordog/mooltipage#59]
This repo contains eslint but even if contributor tries to push changes with lint error, they are able to do that. One better way could be preventing contributors from making any push unless lint issue is resolved

@warriordog, LMK If you think this implementation would be fruitful to the repo, I can work on this. otherwise you can close this.

**Comment by warriordog** [comment]
@Vhndaree Thank you, this is a good idea. There are currently GitHub actions configured to review all PRs and commits, but it would be helpful for a dev to know if there are any errors before they commit. If you can configure a pre-commit hook to run an NPM script, then it would be very helpful to run at least the "rebuild", "test", "and lint-fix" scripts.
