### ISSUE TITLE
Expand patterns for lint-staged

### ISSUE THREAD

**Issue by warriordog** [warriordog/mooltipage#65]
Currently, the lint-staged config (in .lintstagedrc) looks like this:
```
{
  "./**/*.ts": [
    "npm run lint-fix"
  ]
}
```
This triggers a build and code lint for any modified files before each commit. However, this is limited to just *.ts files currently. The patterns and commands here should be expanded to cover all inputs that could affect the build or lint. At least these changes should be made:

- Match on `.eslintignore` and `.eslintrc.json` to pick up changes to the lint config.
- Match on `tsconfig.json` and `tsconfig.base.json` to pick up changes to the build config. There are multiple `tsconfig.json` files in different folders, so make sure to use a filename match and not a path match.
- Match on `ava.config.js` to pick up changes to unit test config.
- Match on `package.json` to pick up package version changes. Build, tests, and linting should all re-run if package versions change.

The simplest way to handle this is to modify the config like this:
```
{
  "./**/*.{ts,js,json}": [
      "npm run lint"
  ]
}
```
This will trigger a lint on any change to a TS, JS, or JSON file. Testing is needed to make sure that ESLint does not throw errors when asked to link a JSON file, since this change will cause lint-staged to pass any modified JSON files as arguments to ESLint.

Documentation for lint-staged is available [here](https://www.npmjs.com/package/lint-staged).

**Comment by Vhndaree** [comment]
@warriordog I think 
```
{
  "./**/*.{ts,js,json}": [
      "npm run lint",
      "npm build"
  ]
}
```
will be enough since these types of files can make breaking changes.

**Comment by warriordog** [comment]
@Vhndaree 
Thanks, that should work and its a lot simpler than specifying everything individually.

**Comment by Vhndaree** [comment]
@warriordog, recently I noticed that we even don't need to add `json` as a pattern. Because, we are not linting any of `.json` files. And if you think build should be auto run before every changes to be commited, husky will handle this as build command is mentioned in `pre-commit`.

So, I think below is suffice
{
  "./**/*.{ts,js}": [
      "npm run lint"
  ]
}
