### ISSUE TITLE
Docs: headers are not in evenly-descending order

### ISSUE THREAD

**Issue by warriordog** [warriordog/mooltipage#68]
In the documentation site, header classes (h1, h2, h3, etc) currently skip from h1 or h2 straight to h5. These h5s need to be changed to h3s, but the site CSS should be adjusted so that h3 looks like h5 currently does. h4, h5, and h6 will also need to downsized appropriately, so that all the header classes are smaller / less attention-grabbing than the previous one.

**Comment by Vhndaree** [comment]
@warriordog, Since hactoberfest is going on can you label issues (in your opinion doesn't involve breaking changes) as `hactoberfest`?

**Comment by warriordog** [comment]
@Vhndaree Sure, but I thought that issues did not need to be labeled as `hacktoberfest` as long as the repository is tagged that way. Has that changed?

**Comment by Vhndaree** [comment]
@warriordog, `hactoberfest` tag can makes the repo appear in lots of searches. By this tag may be the repo can get more attention that it deserves.

**Comment by warriordog** [comment]
@Vhndaree Very good point, thanks for the suggestion!

**Comment by cnp96** [comment]
@warriordog Can I work on this?
